# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3e66724c1be3bedca4c3a4b1ef8db4c437d8bfcb42c23d2b1cb86db4e0dc9f44876f5d6534ede559ef002dc6c293d659d3926f4f9910207d3dac19cd198e8023

test:
  secret_key_base: b849d0e5cb0dba873f0d7f2dcb3b96f8c2d38bbe30d18cc9352d9bea860319905e46a46a5130cd4bd53681fb1e83c46817b1e915b21a5259f1ca4751d32b1111

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
